DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
    PRODUCTID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    BRAND VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
	COLOR VARCHAR(16) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_ON TIMESTAMP
);